#!/usr/bin/env python3
"""Arithmetic Unit Lab - bundle regression and synthesis results for the website.

Author: Nitish Sundarraj

Reads   results/tests.log          (scripts/run_tests.sh | tee results/tests.log)
        results/synthesis.json     (scripts/synth_sweep.py)
Writes  docs/data/site-data.js     (window.AU_DATA, loaded by docs/index.html)
"""
from __future__ import annotations

import datetime as dt
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RES = ROOT / "results"


def parse_tests(text: str) -> list[dict]:
    out = []
    for line in text.splitlines():
        m = re.match(r"\s+ok\s+PASS (\S+)(.*)$", line)
        if m:
            tb, rest = m.group(1), m.group(2)
            c = re.search(r"(?:checks|results|vectors|frames)=(\d+)", rest)
            out.append({"tb": tb, "params": rest.strip(), "checks": int(c.group(1)) if c else 0, "pass": True})
            continue
        m = re.match(r"\s+ok\s+pytest: (\d+) passed", line)
        if m:
            out.append({"tb": "pytest", "params": "", "checks": int(m.group(1)), "pass": True})
            continue
        m = re.match(r"\s+ok\s+node: PASS \S+ checks=(\d+)", line)
        if m:
            out.append({"tb": "js", "params": "", "checks": int(m.group(1)), "pass": True})
            continue
        m = re.match(r"\s+FAIL\s+(\S+)(.*)$", line)
        if m:
            out.append({"tb": m.group(1), "params": m.group(2).strip(), "checks": 0, "pass": False})
    return out


def main() -> int:
    data = {"generated": dt.date.today().isoformat()}
    tl = RES / "tests.log"
    data["tests"] = parse_tests(tl.read_text()) if tl.exists() else []
    sj = RES / "synthesis.json"
    data["synth"] = json.loads(sj.read_text()) if sj.exists() else {"rows": []}
    # the site presents the current design only; reference rows stay in results/
    data["synth"]["rows"] = [r for r in data["synth"].get("rows", [])
                             if r.get("group") != "legacy" and not r.get("name", "").startswith("2023")]
    out = ROOT / "docs" / "data" / "site-data.js"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("/* generated by scripts/build_site_data.py - do not edit */\nwindow.AU_DATA = "
                   + json.dumps(data, separators=(",", ":")) + ";\n")
    print(f"wrote {out.relative_to(ROOT)}: {len(data['tests'])} test runs, "
          f"{len(data['synth'].get('rows', []))} synthesis rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
