--------------------------------------------------------------------------------
-- Arithmetic Unit Lab                           tb/tb_arith_unit_vectors.vhd
-- Author : Nitish Sundarraj
--
-- Drives arith_unit through its real handshake with vectors generated by the
-- golden model (model/au_model.py) and checks, for every vector:
--   * load is a single-cycle pulse (what the specification describes)
--   * status is '0' from the load edge until the result is ready
--   * status rises after exactly the model's latency
--   * P, err and ovf equal the model
--   * P, status, err and ovf hold for 3 more cycles while the inputs change
-- Every 9th vector is preceded by a decoy load that is interrupted 2 to 6
-- cycles later, so "load while busy restarts" is exercised as well.
-- Ends with PASS/FAIL; FAIL stops the simulation with a non-zero exit code.
--------------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb_arith_unit_vectors is
  generic (
    N         : positive := 8;
    CW        : positive := 8;
    DW        : positive := 8;
    MULT_ARCH : string   := "DADDA";
    CPA_ARCH  : string   := "KOGGE_STONE";
    VECTORS   : string   := "tb/vectors/arith_unit_n8.txt"
  );
end entity tb_arith_unit_vectors;

architecture sim of tb_arith_unit_vectors is
  constant T : time := 10 ns;
  signal clk     : std_logic := '0';
  signal reset_n : std_logic := '0';
  signal load    : std_logic := '0';
  signal A, B    : std_logic_vector(N - 1 downto 0) := (others => '0');
  signal C       : std_logic_vector(CW - 1 downto 0) := (others => '0');
  signal D       : std_logic_vector(DW - 1 downto 0) := (others => '0');
  signal sgn, fsel, status, err, ovf : std_logic := '0';
  signal P       : std_logic_vector(2 * N - 1 downto 0);
  signal done    : boolean := false;

  procedure read_hex (l : inout line; v : out unsigned) is
    variable ch  : character;
    variable acc : unsigned(v'length + 3 downto 0) := (others => '0');
    variable dig : natural;
    variable got : boolean := false;
  begin
    loop
      read(l, ch);
      exit when ch /= ' ';
    end loop;
    loop
      case ch is
        when '0' to '9' => dig := character'pos(ch) - character'pos('0');
        when 'A' to 'F' => dig := character'pos(ch) - character'pos('A') + 10;
        when 'a' to 'f' => dig := character'pos(ch) - character'pos('a') + 10;
        when others     => exit;
      end case;
      acc := shift_left(acc, 4) + dig;
      got := true;
      exit when l'length = 0;
      read(l, ch);
    end loop;
    assert got report "vector file: hex field expected" severity failure;
    v := acc(v'length - 1 downto 0);
  end procedure;
begin
  clk <= not clk after T / 2 when not done;

  dut : entity work.arith_unit
    generic map (N => N, CW => CW, DW => DW, MULT_ARCH => MULT_ARCH, CPA_ARCH => CPA_ARCH)
    port map (clk => clk, reset_n => reset_n, load => load, A => A, B => B, C => C, D => D,
              sgn => sgn, fsel => fsel, status => status, err => err, ovf => ovf, P => P);

  stim : process
    file f          : text;
    variable st     : file_open_status;
    variable l      : line;
    variable ua, ub : unsigned(N - 1 downto 0);
    variable uc     : unsigned(CW - 1 downto 0);
    variable ud     : unsigned(DW - 1 downto 0);
    variable up     : unsigned(2 * N - 1 downto 0);
    variable u1     : unsigned(0 downto 0);
    variable vs, vf, ve, vo : std_logic;
    variable lat, cycles : natural;
    variable count, errors : natural := 0;

    procedure fail (msg : string) is
    begin
      errors := errors + 1;
      if errors <= 12 then
        report "vector " & integer'image(count) & ": " & msg severity error;
      end if;
    end procedure;
  begin
    file_open(st, f, VECTORS, read_mode);
    assert st = open_ok report "cannot open " & VECTORS severity failure;

    reset_n <= '0';
    wait for 3 * T;
    wait until falling_edge(clk);
    reset_n <= '1';
    wait until falling_edge(clk);
    assert status = '0' and unsigned(P) = 0 report "outputs not cleared by reset" severity error;

    while not endfile(f) loop
      readline(f, l);
      next when l'length = 0 or l(l'low) = '#';
      read_hex(l, ua); read_hex(l, ub); read_hex(l, uc); read_hex(l, ud);
      read_hex(l, u1); vs := u1(0);
      read_hex(l, u1); vf := u1(0);
      read_hex(l, up);
      read_hex(l, u1); ve := u1(0);
      read_hex(l, u1); vo := u1(0);
      read(l, lat);
      count := count + 1;

      if count mod 9 = 0 then                  -- decoy load, interrupted
        A <= not std_logic_vector(ua); B <= std_logic_vector(ub); C <= std_logic_vector(uc + 1);
        D <= not std_logic_vector(ud); sgn <= not vs; fsel <= vf;
        load <= '1';
        wait until falling_edge(clk);
        load <= '0';
        for k in 1 to 1 + (count / 9) mod 5 loop   -- interrupt 1..5 cycles in
          wait until falling_edge(clk);
        end loop;
      end if;

      A <= std_logic_vector(ua); B <= std_logic_vector(ub);
      C <= std_logic_vector(uc); D <= std_logic_vector(ud);
      sgn <= vs; fsel <= vf;
      load <= '1';
      wait until falling_edge(clk);            -- the load edge has passed
      load <= '0';
      A <= (others => 'X'); B <= (others => 'X');   -- inputs are don't-care now
      C <= (others => 'X'); D <= (others => 'X');
      sgn <= 'X'; fsel <= 'X';
      cycles := 0;
      if status /= '0' then fail("status not cleared by load"); end if;
      while status /= '1' and cycles < 4 * N + 20 loop
        wait until falling_edge(clk);
        cycles := cycles + 1;
      end loop;
      if cycles /= lat then
        fail("latency " & integer'image(cycles) & " expected " & integer'image(lat));
      end if;
      if unsigned(P) /= up then
        fail("P = " & integer'image(to_integer(unsigned(P(P'high downto 1)))) & "*2+" & std_logic'image(P(0))
             & " expected " & integer'image(to_integer(up(up'high downto 1))) & "*2+" & std_logic'image(up(0)));
      end if;
      if err /= ve then fail("err wrong"); end if;
      if ovf /= vo then fail("ovf wrong"); end if;
      for k in 1 to 3 loop                     -- result must hold
        wait until falling_edge(clk);
        if status /= '1' or unsigned(P) /= up or err /= ve or ovf /= vo then
          fail("result did not hold");
          exit;
        end if;
      end loop;
    end loop;
    file_close(f);

    -- reset in the middle of a computation clears everything
    A <= (others => '1');
    B <= (others => '1'); C <= (others => '0'); D <= (others => '0');
    sgn <= '0'; fsel <= '1';
    C(0) <= '1';
    load <= '1';
    wait until falling_edge(clk);
    load <= '0';
    wait until falling_edge(clk);
    reset_n <= '0';
    wait for 1 ns;
    if status /= '0' or unsigned(P) /= 0 or err /= '0' then fail("async reset did not clear outputs"); end if;
    wait until falling_edge(clk);
    reset_n <= '1';
    for k in 1 to 4 * N + 10 loop
      wait until falling_edge(clk);
      if status /= '0' then fail("unit restarted by itself after reset"); exit; end if;
    end loop;

    if errors = 0 then
      report "PASS tb_arith_unit_vectors N=" & integer'image(N) & " CW=" & integer'image(CW)
           & " DW=" & integer'image(DW) & " " & MULT_ARCH & "/" & CPA_ARCH
           & " vectors=" & integer'image(count);
    else
      report "FAIL tb_arith_unit_vectors errors=" & integer'image(errors) & " of " & integer'image(count)
        severity failure;
    end if;
    done <= true;
    wait;
  end process;
end architecture sim;
